import type { Locale } from "@/lib/content";

// Интерфейсные тексты дизайна в стиле Karo. Факты берутся из agency-content.
const ru = {
  metaTitle: "Merlin Agency: платный трафик и SEO, которые приводят клиентов",
  metaDescription:
    "Контекстная реклама, SEO, таргет, маркетплейсы и аналитика. Больше 10 лет в digital-маркетинге, проекты в 14 странах.",
  years: "( 10+ лет )",
  tagline: "( Performance-маркетинг )",
  heroTitle: "Платный трафик и SEO, которые приводят клиентов",
  heroText:
    "Контекстная реклама, SEO, таргет и аналитика в одних руках. Больше 10 лет в digital и проекты в 14 странах.",
  discuss: "Обсудить",
  stickers: ["+320% заявок", "CTR 9,65%", "№1 среди франшиз", "Лид $3,2"],
  bracketLeft: "Смотрим не на клики",
  bracketRight: "а на клиентов",
  nichesBracket: "От медицины до B2B-производства",
  statementTitle: "Агентство с опытом в 14 странах",
  statementNote: "( Батуми. Удалённо )",
  casesPill: "Кейсы",
  statementRight: "контекст, SEO, таргет, маркетплейсы, сайты и аналитика под ключ",
  founder:
    "Агентство основал digital-маркетолог, который руководил отделами маркетинга, работал в агентствах и сам пишет сервисы для сбора данных и отчётов.",
  statsTitle: "Цифры",
  statsNote: "( из реальных проектов )",
  servicesTitle: "Услуги",
  servicesNote: "( 09 направлений )",
  servicesIntro: "Порядок не случайный: сверху то, в чём экспертиза глубже всего.",
  band: "Клиенты, а не клики",
  casesTitle: "Кейсы",
  casesNote: "( ниша, задача, результат )",
  casesIntro: "Медицина, общепит, EdTech, недвижимость, право и B2B. Цифры из реальных проектов.",
  manifestTitle: "Merlin Agency закрывает трафик целиком: от стратегии до аналитики",
  manifestText:
    "Яндекс Директ с 2017 года, Google Ads, SEO, таргет и маркетплейсы. Руководство отделом маркетинга, найм удалённых специалистов и подрядчиков под точечные задачи. Тексты, сценарии и подача от человека с образованием в телевизионной журналистике. Ведение клиента на русском, английском и грузинском.",
  manifestBracket: "Одна точка ответственности",
  approachTitle: "Подход",
  approachNote: "( 5 шагов )",
  nichesTitle: "Ниши",
  geoTitle: "География",
  geoNote: "( 14 стран )",
  auditTitle: "Аудит",
  auditNote: "( бесплатно )",
  auditLead: "Отчёт по конкурентам, SEO и рекламе за пару минут",
  auditSources:
    "Данные из публичных источников: ваш сайт, органическая выдача Google, Google Ads Transparency Center и Meta Ad Library.",
  auditButton: "Получить аудит",
  ctaTitle: ["Обсудим", "проект"],
  ctaText:
    "Расскажите о бизнесе и задаче в Telegram или WhatsApp. Разберём текущую рекламу и сайт и предложим, с чего начать.",
  ctaTelegram: "Написать в Telegram",
  ctaAudit: "Бесплатный аудит сайта",
  footerAudit: "Аудит",
  footerCity: "Батуми",
  footerRemote: "Работаем удалённо",
  // Шапка и карусель
  headerAudit: "Бесплатный аудит",
  headerWrite: "Написать",
  menu: "Меню",
  close: "Закрыть",
  sectionsLabel: "Разделы",
  toTop: "Merlin Agency, наверх",
  task: "Задача. ",
  done: "Что сделали. ",
  swipe: "[ Листайте кейсы ]",
  prevCase: "Предыдущий кейс",
  nextCase: "Следующий кейс",
  langSwitch: "Switch to English",
};

export type AgencyCopy = typeof ru;

const en: AgencyCopy = {
  metaTitle: "Merlin Agency: paid traffic and SEO that bring in clients",
  metaDescription:
    "Search ads, SEO, paid social, marketplaces and analytics. 10+ years in digital marketing, projects in 14 countries.",
  years: "( 10+ years )",
  tagline: "( Performance marketing )",
  heroTitle: "Paid traffic and SEO that bring in clients",
  heroText:
    "Search ads, SEO, paid social and analytics in one pair of hands. 10+ years in digital and projects in 14 countries.",
  discuss: "Let's talk",
  stickers: ["+320% leads", "CTR 9.65%", "#1 franchise", "Lead $3.20"],
  bracketLeft: "Not clicks",
  bracketRight: "but clients",
  nichesBracket: "From healthcare to B2B manufacturing",
  statementTitle: "An agency with experience in 14 countries",
  statementNote: "( Batumi. Remote )",
  casesPill: "Cases",
  statementRight: "search, SEO, paid social, marketplaces, websites and analytics, end to end",
  founder:
    "The agency was founded by a digital marketer who has run marketing departments, worked at agencies and builds in-house tools for data collection and reporting.",
  statsTitle: "Numbers",
  statsNote: "( from real projects )",
  servicesTitle: "Services",
  servicesNote: "( 09 services )",
  servicesIntro: "The order is deliberate: the deepest expertise is at the top.",
  band: "Clients, not clicks",
  casesTitle: "Cases",
  casesNote: "( niche, task, result )",
  casesIntro:
    "Healthcare, food service, EdTech, real estate, law and B2B. Numbers from real projects.",
  manifestTitle: "Merlin Agency handles your traffic end to end: from strategy to analytics",
  manifestText:
    "Yandex Direct since 2017, Google Ads, SEO, paid social and marketplaces. Running a marketing department, hiring remote specialists and contractors for specific tasks. Copy, scripts and storytelling from someone with a degree in television journalism. Client communication in Russian, English and Georgian.",
  manifestBracket: "One point of responsibility",
  approachTitle: "Approach",
  approachNote: "( 5 steps )",
  nichesTitle: "Niches",
  geoTitle: "Geography",
  geoNote: "( 14 countries )",
  auditTitle: "Audit",
  auditNote: "( free )",
  auditLead: "A report on competitors, SEO and ads in a couple of minutes",
  auditSources:
    "Public data only: your website, Google organic results, Google Ads Transparency Center and Meta Ad Library. The report is in Russian.",
  auditButton: "Get the audit",
  ctaTitle: ["Start a", "project"],
  ctaText:
    "Tell us about your business and goals on Telegram or WhatsApp. We will review your current ads and website and suggest where to start.",
  ctaTelegram: "Message on Telegram",
  ctaAudit: "Free website audit",
  footerAudit: "Audit",
  footerCity: "Batumi",
  footerRemote: "Working remotely",
  headerAudit: "Free audit",
  headerWrite: "Message us",
  menu: "Menu",
  close: "Close",
  sectionsLabel: "Sections",
  toTop: "Merlin Agency, back to top",
  task: "Task. ",
  done: "What we did. ",
  swipe: "[ Swipe through cases ]",
  prevCase: "Previous case",
  nextCase: "Next case",
  langSwitch: "Перейти на русский",
};

export const AGENCY_COPY: Record<Locale, AgencyCopy> = { ru, en };
